sudo: false
language: ruby
rvm: 2.4.1

addons:
  postgresql: '9.6'

before_install: gem install bundler -v 1.16.1

before_script:
  - psql -c 'create database election_test;' -U postgres

script:
  - RAILS_ENV=test rake db:migrate --trace
  - rake db:seed
  - rake ci
